# Generated by Django 4.1 on 2022-08-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tile',
            new_name='title',
        ),
    ]
